package com.study.bmservice.dto;

public class Margin {
//     "account": "long",
//             "currency": "symbol",
//             "riskLimit": "long",
//             "prevState": "symbol",
//             "state": "symbol",
//             "action": "symbol",
//             "amount": "long",
//             "pendingCredit": "long",
//             "pendingDebit": "long",
//             "confirmedDebit": "long",
//             "prevRealisedPnl": "long",
//             "prevUnrealisedPnl": "long",
//             "grossComm": "long",
//             "grossOpenCost": "long",
//             "grossOpenPremium": "long",
//             "grossExecCost": "long",
//             "grossMarkValue": "long",
//             "riskValue": "long",
//             "taxableMargin": "long",
//             "initMargin": "long",
//             "maintMargin": "long",
//             "sessionMargin": "long",
//             "targetExcessMargin": "long",
//             "varMargin": "long",
//             "realisedPnl": "long",
//             "unrealisedPnl": "long",
//             "indicativeTax": "long",
//             "unrealisedProfit": "long",
//             "syntheticMargin": "long",
//             "walletBalance": "long",
//             "marginBalance": "long",
//             "marginBalancePcnt": "float",
//             "marginLeverage": "float",
//             "marginUsedPcnt": "float",
//             "excessMargin": "long",
//             "excessMarginPcnt": "float",
//             "availableMargin": "long",
//             "withdrawableMargin": "long",
//             "timestamp": "timestamp",
//             "grossLastValue": "long",
//             "commission": "float"
}
