#spring.profiles.active: @activeProfiles@
spring.jackson.serialization.writeDatesAsTimestamps: false
spring.mvc.throw-exception-if-no-handler-found: true
spring.resources.add-mappings: false
#server.error.whitelabel.enabled: false

spring:
    datasource:
        driverClassName: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin://@10.202.30.27:1521:SSORCL
        username: username
        password: password
        initialSize: 10
        maxActive: 100
        maxIdle: 100
        minIdle: 10
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        minEvictableIdleTimeMillis: 60000
        timeBetweenEvictionRunsMillis: 30000

#
#spring:
#    datasource:
#        driverClassName: com.mysql.cj.jdbc.Driver
#        initialSize: 10
#        maxActive: 100
#        maxIdle: 100
#        minIdle: 10
#        validationQuery: SELECT 1 FROM DUAL
#        testWhileIdle: true
#        minEvictableIdleTimeMillis: 60000
#        timeBetweenEvictionRunsMillis: 30000
#
#---
#
#spring.profiles: prod
#
### database connection property.
#spring:
#    datasource:
#        url: jdbc:mysql://10.202.30.28/CC?serverTimezone=Asia/Seoul
#        username: username
#        password: password
#
#
#---
#
#spring.profiles: dev
#
#spring:
#    datasource:
#        url: jdbc:mysql://172.29.232.32/CC?useUnicode=true&serverTimezone=Asia/Seoul
#        username: username
#        password: password
#
#
#---
#
#spring.profiles: local, default
#
#spring:
#    datasource:
#        url: jdbc:mysql://10.202.30.28/CC?serverTimezone=Asia/Seoul
#        username: username
#        password: password
#
#
#---