-- oracle
create table tempc
(
    id number not null,
    name varchar2(25 byte)
);
CREATE TABLE TEMP_STAT
(
    ACCOUNT_ID NUMBER,
	CURRENT_ACCOUNT_ID NUMBER,
	SID NUMBER,
	GID NUMBER,
	WIN NUMBER,
	DURATION NUMBER,
	SEASON NUMBER,
	VERSION VARCHAR2(20 BYTE),
	CREATED_DATE DATE,
	START_TIME TIMESTAMP (6),
	CID NUMBER,
	OWNER NUMBER,
	LOSE NUMBER
);
